on:
  #push:
  #  branches:
  #  - main
  #pull_request:
  #  branches:
  #  - main
  #schedule:
  #- cron: "0 15 * * *"
  workflow_dispatch:
  
jobs:
  test:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup Zig Compiler
      uses: mlugg/setup-zig@v1.2.1
      with:
       version: 0.13.0

    - name: Export GitHub Actions Cache environment variables
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

    - name: Enable GitHub Actions Cache backend
      uses: actions/github-script@v7
      with:
        script: |
          core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
          core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
            
    - name: some vcpkg task
      run: "${{ github.workspace }}/vcpkg/vcpkg install"
      env:
        X_VCPKG_ASSET_SOURCES: "clear;x-azurl, file://D:/vcpkg/asset-cache, {{ secrets.SAS }}, readwrite"
        VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    - name: Build
      run: zig build
