on:
  #push:
  #  branches:
  #  - main
  #pull_request:
  #  branches:
  #  - main
  #schedule:
  #- cron: "0 15 * * *"
  workflow_dispatch:
  
jobs:
  test:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Setup Zig Compiler
      uses: mlugg/setup-zig@v1.2.1
      with:
       version: 0.13.0

    - name: run-vcpkg
      uses: lukka/run-vcpkg@v11.5
      with:
        runVcpkgInstall: true

    - name: Build
      run: zig build
